#Basic GitHubActions workflow
name: CI
#Trigger the job
on: 
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:
 #Testing
  build:
    #
    runs-on: ['self-hosted', 'macOS', 'X64']
    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hellow, world!
    
